### ISSUE TITLE
Not compatible with kirby grid

### ISSUE THREAD

**Issue by schnti** [SebastianEberlein/kirby-markdown-field#3]
![screenshot 2017-03-26 13 13 30](https://cloud.githubusercontent.com/assets/1868482/24330770/187ef2d2-1226-11e7-9bb3-a4f34c362696.png)

```
fields:
  title:
    label: Title
    type:  text
  text:
    label: Spalte 1
    type:  markdown
    width: 1/2
  text2:
    label: Spalte 2
    type:  markdown
    width: 1/2
```
